### ISSUE TITLE
Can't remove accidentally imported files

### ISSUE THREAD

**Issue by tushantin** [geigi/cozy#100]
At my first start, I accidentally placed the wrong directory to search from (and for some reason, it requires me to have two directories to scan from, and not allow me to delete the other directory). I want to delete some books that were loaded onto the app, but for some reason it won't let me remove it. There's no Remove option anywhere, nor will it right-click.

**Comment by geigi** [comment]
You should be able to remove the directory that is not set as the default directory (marked with the Checkmark). If you've selected the worng directory first, you can remove it only after adding a second one and setting it as default, or you can just change the first directory and start a rescan from the options menu. To remove items that are accidentally imported first remove the wrong directory from the settings and then start the rescan. This will remove all books from cozy that are not longer in the given directories.

**Comment by tushantin** [comment]
I wasn't able to select only "one" default, because there were two directories being recognized as default, and I couldn't change or remove them. On top of that, I did change those default directories to something else, but that did not remove the books. Maybe it' because the scanning / rescanning on this app is broken, and it stops at some point but doesn't cancel. As a result, it just couldn't import all the books in that specified directory. :/ 

I had to remove the app because it wasn't as usable to me. But I'll reinstall the app so I can post the error messages here to elaborate what I mean. (I'm using Ubuntu with Flatpak installation, BTW.)

**Comment by tushantin** [comment]
Okay, this is the error I keep getting every time I try to scan. For some reason, every time it hits "Exception in thread" in the terminal it stops checking for books, even though the app itself seems like it's still loading those books forever. I wish there was a "cancel" button for loading at this point, but even then the fact that it won't read the directories properly seems to bug me. I can play some of the files quite fine with another app, but for some reason Cozy still skips them too. 

Also, the app seems to recognize two directories as "default" (both having check-marks). How do I remove one of them? There doesn't seem to be any option to remove one of them from defaults. 

```
INFO:importer:Could not get tag tracknumber for file /Drive/All Stuff/Books/Galexczy-Part01.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag ©wrt for file /Drive/All Stuff/Books/chwxew/01 chwxew 1.m4a
INFO:importer:'©wrt'
INFO:importer:Could not get tag ©wrt for file /Drive/All Stuff/Books/chwxew/02 chwxew 2.m4a
INFO:importer:'©wrt'
INFO:importer:Could not get tag ©wrt for file /Drive/All Stuff/Books/chwxew/03 chwxew 3.m4a
INFO:importer:'©wrt'
INFO:importer:Could not get tag ©wrt for file /Drive/All Stuff/Books/chwxew/04 chwxew 4.m4a
INFO:importer:'©wrt'
INFO:importer:Could not get tag ©wrt for file /Drive/All Stuff/Books/chwxew/05 chwxew 5.m4a
INFO:importer:'©wrt'
INFO:importer:Could not get tag ©wrt for file /Drive/All Stuff/Books/chwxew/06 chwxew 6.m4a
INFO:importer:'©wrt'
INFO:importer:Could not get tag ©wrt for file /Drive/All Stuff/Books/chwxew/07 chwxew 7.m4a
INFO:importer:'©wrt'
INFO:importer:Could not get tag album for file /Drive/Audiobooks/rdpdrk.mp3
INFO:importer:'TALB'
INFO:importer:Could not get tag title for file /Drive/Audiobooks/rdpdrk.mp3
INFO:importer:'TIT2'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/rdpdrk.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag album for file /Drive/Audiobooks/tsurs.mp3
INFO:importer:'TALB'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/tsurs.mp3
INFO:importer:'TRCK'
WARNING:importer:Track /Drive/Audiobooks/Librevox/yexiayi.mp3 is no valid MP3 file. Skipping...
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Librevox/1914.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Librevox/Faust.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 001.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 002.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 003.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 004.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 005.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 006.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 007.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 008.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 009.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 010.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 011.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 012.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 013.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 014.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 015.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 016.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 017.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 018.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 019.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 020.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 021.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 022.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 023.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 024.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 025.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 026.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 027.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 028.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 029.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 030.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 031.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 032.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 033.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 034.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 035.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Dante Alighieri/thecon 036.mp3
INFO:importer:'TRCK'
WARNING:importer:Track /Drive/Audiobooks/Adventures of Huckleberry Finn/part 01.mp3 is no valid MP3 file. Skipping...
WARNING:importer:Track /Drive/Audiobooks/Adventures of Huckleberry Finn/part 02.mp3 is no valid MP3 file. Skipping...
WARNING:importer:Track /Drive/Audiobooks/Adventures of Huckleberry Finn/part 03.mp3 is no valid MP3 file. Skipping...
INFO:importer:Could not get tag album for file /Drive/Audiobooks/BAM/bam.mp3
INFO:importer:'TALB'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Leaves of Grass/bk-Part01.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Leaves of Grass/bk-Part02.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Leaves of Grass/bk-Part03.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Leaves of Grass/bk-Part04.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Leaves of Grass/bk-Part05.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Leaves of Grass/bk-Part06.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Leaves of Grass/bk-Part07.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Leaves of Grass/bk-Part08.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Leaves of Grass/bk-Part09.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Leaves of Grass/bk-Part10.mp3
INFO:importer:'TRCK'
INFO:importer:Could not get tag tracknumber for file /Drive/Audiobooks/Leaves of Grass/bk-Part11.mp3
INFO:importer:'TRCK'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/app/lib/python3.5/site-packages/cozy/importer.py", line 81, in update_database
    imported = import_file(file, directory, path)
  File "/app/lib/python3.5/site-packages/cozy/importer.py", line 166, in import_file
    mp3 = TrackContainer(MP3(track.path), path)
  File "/app/lib/python3.5/site-packages/mutagen/_file.py", line 49, in __init__
    self.load(*args, **kwargs)
  File "/app/lib/python3.5/site-packages/mutagen/_util.py", line 140, in wrapper
    return func(self, h, *args, **kwargs)
  File "/app/lib/python3.5/site-packages/mutagen/id3/_file.py", line 406, in load
    self.info = self._Info(fileobj, offset)
  File "/app/lib/python3.5/site-packages/mutagen/_util.py", line 169, in wrapper
    return func(*args, **kwargs)
  File "/app/lib/python3.5/site-packages/mutagen/mp3/__init__.py", line 403, in __init__
    raise HeaderNotFoundError("can't sync to MPEG frame")
mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame
```

**Comment by geigi** [comment]
Ok this sounds like you're experiencing two bugs, there should never be two default directories... And it seems like the import failed on one of your mp3s and this completely stops the import progress and leaves cozy in a broken state. Thanks for posting the log, I'll look into it tomorrow :)

**Comment by tushantin** [comment]
Sweet! Happy to help. :)

**Comment by geigi** [comment]
Sorry for the delay man I haven't forgotten your issue, just didn't find the time to look into it yet...

**Comment by geigi** [comment]
Ok so I'm not entirely sure how the two default location thing happened but I've now implemented a fix that resets the locations to only one default at each startup.
I did also some research on the "can't sync to MPEG frame" error and it seems like the audio tag library I'm using will not be able to load this file. Sadly I could not find something about why this happens and therefore Cozy will not import it. Maybe you can fix this issue by reencoding the file (which is really not a nice solution)...
But some good news: I've implemented a mechanism so that cozy will not stop importing when an error like this happens. Instead you'll get a dialog at the end of the import with all files listed that cozy was not able to import.
This will be included in the next version :)

**Comment by tushantin** [comment]
Oh, sweet! Glad to know that it'll be fixed by the next release. Can't wait! :) And thank you very much for looking into this.

**Comment by tushantin** [comment]
BTW, if I really do need to reencode the files, what settings would I ideally need to do so? And what might be a faster way of doing it for multiple files?

**Comment by geigi** [comment]
The most important thing is that you use id3v2 tags (the newest version) which should be used by most converters by default. For the audio quality I recommend using the same settings that the files already have. For example you can use soundconverter (http://soundconverter.org/) to convert the files and easytag for tagging (https://wiki.gnome.org/Apps/EasyTAG). Let me know when you have any questions ;)

**Comment by geigi** [comment]
Cozy 0.5.5 is now out! Let me know if you have any issues :)

**Comment by tushantin** [comment]
Quick observation about your importer (I hope my comment doesn't "reopen" the issue, because this is just an observation, not an issue). 

I noticed that some of the files that Cozy fails to import aren't corrupted at all -- even though Cozy says that it's possibly because the files are either corrupted, not audio-files, or just not the formats Cozy supports. I can listen to those files in other players like Rhythmbox and Totem. 

I did a bit of tinkering, based on your earlier suggestion, and it turns out that it may not be the file itself that's the problem, but the id3v2 tags you mentioned. If a file lacks those tags for Cozy to (presumably) know where to place in a grid, then it fails to import. But that just isn't specified in the "could not be imported" pop-up box, so unless the user is tech-savy the just wouldn't know what the problem might be. 

What I did was install EasyTAG as you suggested and add in the necessary tags: Artist, Album, Name, Track-numbers and cover image. Then Cozy imported the files just fine without any hiccups.

**Comment by tushantin** [comment]
BTW, besides just that, I love the new fixes and features! Thanks for the blacklist box and the right-click remove option! It makes everything so much easier.

**Comment by geigi** [comment]
Hey thanks for your input! You're right, I thought about this and my idea was that when there are no tags the file name will be used for the track name and the folder name for the book name. But I never thought about the case when no tags are available at all. I'm using the tags to verify if a file is actually an audio file or not. When there are no tags, a file will not be recognized as audio file. So I have to think about a new way to test the files for audio files. Thanks again for all your help, I really appreciate it!

**Comment by tushantin** [comment]
You're welcome. Happy to help! :)
