### ISSUE TITLE
Unable to import music

### ISSUE THREAD

**Issue by megatux** [geigi/cozy#120]
### Bug/Feature description
When trying to import music, it keeps "working" forever...actually, there is an exception in the console, probably a bad "migration" from a previous version. Maybe a rmdir of config? Anyway, I think that a good strategy for error handling is to stop the _refresh_ animation if there is an error.

```
Exception in thread UpdateDatabaseThread:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/peewee.py", line 2576, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: no such table: artworkcache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/cozy/importer.py", line 82, in update_database
    artwork_cache.delete_artwork_cache()
  File "/usr/lib/python3/dist-packages/cozy/artwork_cache.py", line 52, in delete_artwork_cache
    q.execute()
  File "/usr/lib/python3/dist-packages/peewee.py", line 1525, in inner
    return method(self, database, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/peewee.py", line 1596, in execute
    return self._execute(database)
  File "/usr/lib/python3/dist-packages/peewee.py", line 2015, in _execute
    return self.handle_result(database, cursor)
  File "/usr/lib/python3/dist-packages/peewee.py", line 2026, in handle_result
    return database.rows_affected(cursor)
  File "/usr/lib/python3/dist-packages/peewee.py", line 2652, in rows_affected
    return cursor.rowcount
  File "/usr/lib/python3/dist-packages/playhouse/sqliteq.py", line 94, in rowcount
    self._wait()
  File "/usr/lib/python3/dist-packages/playhouse/sqliteq.py", line 63, in _wait
    raise self._exc
  File "/usr/lib/python3/dist-packages/playhouse/sqliteq.py", line 178, in execute
    cursor = self.database._execute(obj.sql, obj.params, obj.commit)
  File "/usr/lib/python3/dist-packages/peewee.py", line 2583, in execute_sql
    self.commit()
  File "/usr/lib/python3/dist-packages/peewee.py", line 2376, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/lib/python3/dist-packages/peewee.py", line 175, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/peewee.py", line 2576, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: no such table: artworkcache

```

### System Information
- Operating System: ElementaryOS Loki
- Installation source: 
- Version of cozy: 0.6

**Comment by geigi** [comment]
Sorry for the late answer, I'm quite busy at the moment... The error handling definitely needs improvement there. Did you fix your error by now?

**Comment by megatux** [comment]
No, didn't try again. I would like to try to solve it by deleting my previous configuration/DB. Where is it stored? somewhere inside ~/.config/ ?

**Comment by megatux** [comment]
Worked. Thanks.
