### ISSUE TITLE
Playback stops after each chapter

### ISSUE THREAD

**Issue by Wiblz** [geigi/cozy#131]
### Bug description
Playback stops after each chapter. Timer is turned off. At the end of the chapter this gets printed in terminal:
```
13:44:29 [MainThread  ] [player    ] [INFO ]  Closing.
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/cozy/player.py", line 42, in __on_gst_message next_track()
  File "/app/lib/python3.5/site-packages/cozy/player.py", line 242, in next_track play_pause(next_track)
  File "/app/lib/python3.5/site-packages/cozy/player.py", line 213, in play_pause load_file(track)
  File "/app/lib/python3.5/site-packages/cozy/player.py", line 464, in load_file emit_event("track-changed", track)
  File "/app/lib/python3.5/site-packages/cozy/player.py", line 544, in emit_event function(event, message)
  File "/app/lib/python3.5/site-packages/cozy/book_overview.py", line 286, in __player_changed self.select_track(track, self.ui.is_playing)
  File "/app/lib/python3.5/site-packages/cozy/book_overview.py", line 200, in select_track self.track_box.get_children()), None)
  File "/app/lib/python3.5/site-packages/cozy/book_overview.py", line 199, in <lambda> lambda x: x.track.id == curr_track.id,
AttributeError: 'DiskElement' object has no attribute 'track'
```
### System Information
- Operating System: Ubuntu 18.04
- Installation source: flatpak
- Version of cozy: 0.6.1

**Comment by geigi** [comment]
Thanks for reporting. This bug was fixed in d3dbd579997dc7246e0b9a8bd6440ee51a100bfd but I forgot to push an update. But I'll do so now :)
