### ISSUE TITLE
Changes requested for AppCenter: crashes on opening

### ISSUE THREAD

**Issue by cassidyjames** [geigi/cozy#141]
### Bug/Feature description

Cozy does not open

### Steps to reproduce

Install from the 0.6.4 Juno package, attempt to open.

### System Information
- Operating System: elementary OS 5 Juno
- Installation source: AppCenter testing repository: http://packages.elementary.io/testing/pool/main/c/com.github.geigi.cozy/com.github.geigi.cozy0.6.4-a433d4.deb
- Version of cozy: 0.6.4

```shell
com.github.geigi.cozy 
['/usr/bin/com.github.geigi.cozy']
14:07:13 [MainThread  ] [main      ] [INFO ]  ('elementary', '5.0', 'juno')
14:07:13 [MainThread  ] [main      ] [INFO ]  Starting up cozy 0.6.4
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/cozy/db.py", line 387, in update_db
    next(c for c in db.get_columns("settings") if c.name == "version")
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/com.github.geigi.cozy", line 73, in do_startup
    init_db()
  File "/usr/lib/python3/dist-packages/cozy/db.py", line 129, in init_db
    update_db()
  File "/usr/lib/python3/dist-packages/cozy/db.py", line 389, in update_db
    update_db_1()
  File "/usr/lib/python3/dist-packages/cozy/db.py", line 296, in update_db_1
    migrator.add_column('track', 'crc32', crc32),
  File "/usr/lib/python3/dist-packages/playhouse/migrate.py", line 717, in migrate
    operation.run()
  File "/usr/lib/python3/dist-packages/playhouse/migrate.py", line 144, in run
    getattr(self.migrator, self.method)(*self.args, **kwargs))
  File "/usr/lib/python3/dist-packages/playhouse/migrate.py", line 138, in _handle_result
    self._handle_result(item)
  File "/usr/lib/python3/dist-packages/playhouse/migrate.py", line 135, in _handle_result
    result.run()
  File "/usr/lib/python3/dist-packages/playhouse/migrate.py", line 144, in run
    getattr(self.migrator, self.method)(*self.args, **kwargs))
  File "/usr/lib/python3/dist-packages/playhouse/migrate.py", line 135, in _handle_result
    result.run()
  File "/usr/lib/python3/dist-packages/playhouse/migrate.py", line 144, in run
    getattr(self.migrator, self.method)(*self.args, **kwargs))
  File "/usr/lib/python3/dist-packages/playhouse/migrate.py", line 152, in inner
    return fn(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/playhouse/migrate.py", line 554, in _update_column
    (column_to_update, table))
ValueError: Column "version" does not exist on "settings"

(com.github.geigi.cozy:20867): GLib-GIO-CRITICAL **: 14:07:13.925: GApplication subclass '__main__+Application' failed to chain up on ::startup (from start of override function)
14:07:13 [MainThread  ] [ui        ] [INFO ]  Initialize main window
Traceback (most recent call last):
  File "/usr/bin/com.github.geigi.cozy", line 78, in do_activate
    self.ui.activate()
  File "/usr/lib/python3/dist-packages/cozy/ui.py", line 58, in activate
    self.__init_window()
  File "/usr/lib/python3/dist-packages/cozy/ui.py", line 125, in __init_window
    self.window = self.window_builder.get_object("app_window")
AttributeError: 'CozyUI' object has no attribute 'window_builder'

(com.github.geigi.cozy:20867): GLib-GIO-CRITICAL **: 14:07:13.927: GApplication subclass '__main__+Application' failed to chain up on ::shutdown (from end of override function)
```

**Comment by geigi** [comment]
Is this the Juno deb for sure? It's missing the dependendy `python3-peewee` which is defined in the `deb-packaging-juno` branch: https://github.com/geigi/cozy/blob/deb-packaging-juno/debian/control

**Comment by geigi** [comment]
Nevermind, found the right one

**Comment by eugeneia** [comment]
FWIW 0.6.5 still does not work for me on Juno:
```
com.github.geigi.cozy/bionic 0.6.5 amd64

$ com.github.geigi.cozy
Traceback (most recent call last):
  File "/usr/bin/com.github.geigi.cozy", line 35, in <module>
    from cozy.ui import CozyUI
  File "/usr/lib/python3/dist-packages/cozy/ui.py", line 8, in <module>
    from cozy.book_element import BookElement
  File "/usr/lib/python3/dist-packages/cozy/book_element.py", line 4, in <module>
    import cozy.db as db
  File "/usr/lib/python3/dist-packages/cozy/db.py", line 7, in <module>
    from peewee import __version__ as PeeweeVersion
ModuleNotFoundError: No module named 'peewee'
```

**Comment by geigi** [comment]
I need to look at this tomorrow but it looks like this is a bug in elementary/Houston because the peewee dependency is correctly declared here: https://github.com/geigi/cozy/blob/deb-packaging-juno/debian/control

**Comment by geigi** [comment]
Finally this issue is fixed :)
