### ISSUE TITLE
GST errors can lead to exception

### ISSUE THREAD

**Issue by geigi** [geigi/cozy#283]
```
[ERROR] Traceback (most recent call last):

  File "/app/lib/python3.7/site-packages/cozy/control/player.py", line 54, in __on_gst_message
    emit_event("error", err)

  File "/app/lib/python3.7/site-packages/cozy/control/player.py", line 562, in emit_event
    function(event, message)

  File "/app/lib/python3.7/site-packages/cozy/ui/main_view.py", line 730, in __player_changed
    if is_external(current_track.book):

AttributeError: 'NoneType' object has no attribute 'book'
```

**Comment by geigi** [comment]
No longer present...
