### ISSUE TITLE
SqliteDatabase

### ISSUE THREAD

**Issue by danrabbit** [geigi/cozy#38]
I have a new error on launch ;p

```
daniel@Yoga:~$ com.github.geigi.cozy 
/home/daniel/.local/share/cozy
Traceback (most recent call last):
  File "/usr/bin/com.github.geigi.cozy", line 28, in <module>
    from cozy.ui import CozyUI
  File "/usr/lib/python3/dist-packages/cozy/ui.py", line 4, in <module>
    from cozy.importer import *
  File "/usr/lib/python3/dist-packages/cozy/importer.py", line 16, in <module>
    from cozy.db import *
  File "/usr/lib/python3/dist-packages/cozy/db.py", line 11, in <module>
    db = SqliteDatabase(os.path.join(data_dir, "cozy.db"))
NameError: name 'SqliteDatabase' is not defined
```

**Comment by geigi** [comment]
Thanks Daniel, should be fixed now, I tested it on a clean install ;)
