### ISSUE TITLE
First Import does nothing.

### ISSUE THREAD

**Issue by etrigan63** [geigi/cozy#39]
I am trying to import some audiobooks I have locally on my machine. I can select the folder, but nothing happens after the spinner starts.

**Comment by geigi** [comment]
Hey, can you give me some additional info? Which Linux distro are you using and which version of cozy? What kind of codec (mp3, m4a, ...) are your audiobooks?

**Comment by etrigan63** [comment]
Sure thing, Antergos (Arch) Linux, kernel 4.13.11-1, Cozy 0.3.5 installed from AUR without issues, audiobooks in question are MP3 files and they play fine if I double-click them in Nautilus.

**Comment by geigi** [comment]
@etrigan63 thanks! I think I need some more info: 
Could you run cozy from the terminal with the debug option, rerun the import and paste the results here?
```shell
# first delete the database
rm ~/.local/share/cozy/cozy.db
com.github.geigi.cozy -d
```
Cheers! :)

**Comment by etrigan63** [comment]
Due to hardware compatibility issues, I had to install Ubuntu 17.10 and there is no install of Cozy for that. Could you generate a flatpak or AppImage version?

**Comment by etrigan63** [comment]
A .deb file would be great! Let me know when it is posted!

**Comment by etrigan63** [comment]
Went back to Antergos. Did what you asked and here is the result:

```
INFO:main:Starting up cozy 0.3.5
DEBUG:peewee:('SELECT name FROM sqlite_master WHERE type = ? ORDER BY name;', ('table',))
DEBUG:peewee:('CREATE TABLE "book" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "author" VARCHAR(255) NOT NULL, "reader" VARCHAR(255) NOT NULL, "position" INTEGER NOT NULL, "rating" INTEGER NOT NULL, "cover" BLOB)', [])
DEBUG:peewee:('SELECT name FROM sqlite_master WHERE type = ? ORDER BY name;', ('table',))
DEBUG:peewee:('CREATE TABLE "settings" ("id" INTEGER NOT NULL PRIMARY KEY, "path" VARCHAR(255) NOT NULL, "first_start" INTEGER NOT NULL, "last_played_book_id" INTEGER, FOREIGN KEY ("last_played_book_id") REFERENCES "book" ("id"))', [])
DEBUG:peewee:('CREATE INDEX "settings_last_played_book_id" ON "settings" ("last_played_book_id")', [])
DEBUG:peewee:('SELECT name FROM sqlite_master WHERE type = ? ORDER BY name;', ('table',))
DEBUG:peewee:('CREATE TABLE "track" ("id" INTEGER NOT NULL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, "number" INTEGER NOT NULL, "disk" INTEGER NOT NULL, "position" INTEGER NOT NULL, "book_id" INTEGER NOT NULL, "file" VARCHAR(255) NOT NULL, "length" REAL NOT NULL, "modified" INTEGER NOT NULL, FOREIGN KEY ("book_id") REFERENCES "book" ("id"))', [])
DEBUG:peewee:('CREATE INDEX "track_book_id" ON "track" ("book_id")', [])
DEBUG:peewee:('SELECT Count(*) FROM "settings" AS t1', [])
DEBUG:peewee:('INSERT INTO "settings" ("path", "first_start", "last_played_book_id") VALUES (?, ?, ?)', ['', True, None])
DEBUG:ui:('arch', '17.10', 'ISO-Rolling')
DEBUG:ui:Fanciest design possible
DEBUG:peewee:('SELECT "t1"."id", "t1"."path", "t1"."first_start", "t1"."last_played_book_id" FROM "settings" AS t1 LIMIT 1 OFFSET 0', [])
INFO:main:Cozy will now import all audio files from your selected location.
DEBUG:peewee:('UPDATE "settings" SET "first_start" = ?', [False])
DEBUG:peewee:('UPDATE "settings" SET "path" = ?', ['/home/guru/Music/AudioBooks'])
INFO:ui:Initialize main window
DEBUG:peewee:('SELECT "t1"."id", "t1"."path", "t1"."first_start", "t1"."last_played_book_id" FROM "settings" AS t1 LIMIT 1 OFFSET 0', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."path", "t1"."first_start", "t1"."last_played_book_id" FROM "settings" AS t1 LIMIT 1 OFFSET 0', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."path", "t1"."first_start", "t1"."last_played_book_id" FROM "settings" AS t1 LIMIT 1 OFFSET 0', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."name", "t1"."author", "t1"."reader", "t1"."position", "t1"."rating", "t1"."cover" FROM "book" AS t1', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."name", "t1"."author", "t1"."reader", "t1"."position", "t1"."rating", "t1"."cover" FROM "book" AS t1', [])
DEBUG:peewee:('SELECT Count(*) FROM "book" AS t1', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."path", "t1"."first_start", "t1"."last_played_book_id" FROM "settings" AS t1 LIMIT 1 OFFSET 0', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."path", "t1"."first_start", "t1"."last_played_book_id" FROM "settings" AS t1 LIMIT 1 OFFSET 0', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."name", "t1"."author", "t1"."reader", "t1"."position", "t1"."rating", "t1"."cover" FROM "book" AS t1', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."path", "t1"."first_start", "t1"."last_played_book_id" FROM "settings" AS t1 LIMIT 1 OFFSET 0', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."name", "t1"."author", "t1"."reader", "t1"."position", "t1"."rating", "t1"."cover" FROM "book" AS t1', [])
DEBUG:peewee:('SELECT "t1"."id", "t1"."path", "t1"."first_start", "t1"."last_played_book_id" FROM "settings" AS t1 LIMIT 1 OFFSET 0', [])
DEBUG:peewee:('SELECT Count(*) FROM "track" AS t1 WHERE ("t1"."file" = ?)', ['/home/guru/Music/AudioBooks/E E Smith - Lensman Series/E..E..Smith.-.Lensman.2.-.First.Lensman/First Lensman 151.mp3'])
DEBUG:importer:Importing mp3 /home/guru/Music/AudioBooks/E E Smith - Lensman Series/E..E..Smith.-.Lensman.2.-.First.Lensman/First Lensman 151.mp3
DEBUG:importer:Could not get mp3 tag APIC for file /home/guru/Music/AudioBooks/E E Smith - Lensman Series/E..E..Smith.-.Lensman.2.-.First.Lensman/First Lensman 151.mp3
DEBUG:importer:list index out of range
DEBUG:importer:Could not get mp3 tag TPOS for file /home/guru/Music/AudioBooks/E E Smith - Lensman Series/E..E..Smith.-.Lensman.2.-.First.Lensman/First Lensman 151.mp3
DEBUG:importer:list index out of range
DEBUG:importer:Could not get mp3 tag TCOM for file /home/guru/Music/AudioBooks/E E Smith - Lensman Series/E..E..Smith.-.Lensman.2.-.First.Lensman/First Lensman 151.mp3
DEBUG:importer:'TCOM'
DEBUG:importer:Could not get tag title for file /home/guru/Music/AudioBooks/E E Smith - Lensman Series/E..E..Smith.-.Lensman.2.-.First.Lensman/First Lensman 151.mp3
DEBUG:importer:'TIT2'
DEBUG:importer:Could not get tag tracknumber for file /home/guru/Music/AudioBooks/E E Smith - Lensman Series/E..E..Smith.-.Lensman.2.-.First.Lensman/First Lensman 151.mp3
DEBUG:importer:'TRCK'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/cozy/importer.py", line 62, in update_database
    __importFile(file, path)
  File "/usr/lib/python3.6/site-packages/cozy/importer.py", line 166, in __importFile
    track_number = int(__get_common_tag(track, "tracknumber"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by probonopd** [comment]
> Could you generate a flatpak or __AppImage__ version?

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by geigi** [comment]
@etrigan63 thanks! It'll be fixed in the next release (probably tomorrow) ;)

**Comment by geigi** [comment]
@etrigan63 this should be fixed now. The new version is now in the aur and I've also added a deb file in the github releases section ;)

**Comment by geigi** [comment]
I used EasyTag (available in the repos) for my files, which worked pretty well. Be sure to add the **book reader** to the **Artist** field, and the **book author** to the **Composer** field. This seems to be how most audiobooks are tagged ;)
