### ISSUE TITLE
Cozy not starting up with error packaging.version.InvalidVersion: Invalid version: 'None'

### ISSUE THREAD

**Issue by waferbit** [geigi/cozy#756]
### Bug/Feature description
After installing cozy, I am unable to start it. I get the following error. I get the same error if I install the official one from AUR or the git version (from AUR too).

```
['/usr/bin/cozy-audiobooks']
10:55:28 [MainThread  ] [applicatio] [INFO ]  ('arch', 'rolling', 'n/a')
10:55:28 [MainThread  ] [applicatio] [INFO ]  Starting up cozy 1.2.1
10:55:28 [MainThread  ] [db        ] [INFO ]  SQLite version: 3.40.1
10:55:28 [Thread-1 (ru] [peewee.sql] [INFO ]  writer received shutdown request, exiting.
10:55:29 [MainThread  ] [applicatio] [INFO ]  libhandy version: 1
handle exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/cozy/application.py", line 99, in do_activate
    self.app_controller = AppController(self, main_window_builder, self.ui)
  File "/usr/lib/python3.10/site-packages/cozy/architecture/singleton.py", line 5, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/cozy/app_controller.py", line 52, in __init__
    self.whats_new_window: WhatsNewWindow = WhatsNewWindow()
  File "/usr/lib/python3.10/site-packages/cozy/ui/widgets/whats_new_window.py", line 36, in __init__
    self._fill_window()
  File "/usr/lib/python3.10/site-packages/cozy/ui/widgets/whats_new_window.py", line 54, in _fill_window
    last_launched_version = version.parse(self.app_settings.last_launched_version)
  File "/usr/lib/python3.10/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/usr/lib/python3.10/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'None'
```

### Steps to reproduce
Install cozy through AUR

### System Information
- Operating System: Arch Linux
- Installation source: AUR (yay)
- Version of cozy: cozy 1.2.1 (both git and official version)

**Comment by ThornedRose** [comment]
I also get this issue on Arch Linux

```
$ com.github.geigi.cozy
Gtk-Message: 16:16:49.253: Failed to load module "appmenu-gtk-module"
/home/rose/.local/lib/python3.10/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn(
['/usr/bin/com.github.geigi.cozy']
16:16:49 [MainThread  ] [applicatio] [INFO ]  ('arch', 'rolling', 'n/a')
16:16:49 [MainThread  ] [applicatio] [INFO ]  Starting up cozy 1.2.1
16:16:49 [MainThread  ] [db        ] [INFO ]  SQLite version: 3.41.1
16:16:49 [Thread-1 (ru] [peewee.sql] [INFO ]  writer received shutdown request, exiting.
16:16:49 [MainThread  ] [applicatio] [INFO ]  libhandy version: 1
handle exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/cozy/application.py", line 99, in do_activate
    self.app_controller = AppController(self, main_window_builder, self.ui)
  File "/usr/lib/python3.10/site-packages/cozy/architecture/singleton.py", line 5, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/cozy/app_controller.py", line 52, in __init__
    self.whats_new_window: WhatsNewWindow = WhatsNewWindow()
  File "/usr/lib/python3.10/site-packages/cozy/ui/widgets/whats_new_window.py", line 36, in __init__
    self._fill_window()
  File "/usr/lib/python3.10/site-packages/cozy/ui/widgets/whats_new_window.py", line 54, in _fill_window
    last_launched_version = version.parse(self.app_settings.last_launched_version)
  File "/usr/lib/python3.10/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/usr/lib/python3.10/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'None'
```
Installed from AUR.
OS: Arch Linux x86_64 
Kernel: 6.2.6-arch1-1 
DE: Plasma 5.27.3
Package: cozy-audiobooks 1.2.1-1

**Comment by jeois** [comment]
Please merge suve's [pull request](https://github.com/geigi/cozy/pull/762).  The app will not launch otherwise, neither the binary version nor the git build works.

For temporary workaround, enter into terminal:

`gsettings set com.github.geigi.cozy last-launched-version '1.2.1'` or 
`gsettings set cozy-audiobook last-launched-version 'x.x.x'` depending on which version you installed.

**Comment by rdbende** [comment]
Was fixed in #762

**Comment by hhsissi** [comment]
On an Ubuntu 22.04, I just installed cozy latest available version from repository using

`sudo add-apt-repository ppa:cozy-team/cozy`
`sudo apt-get update`
`sudo apt-get install cozy`

and got crash at startup due to the issue mentionned above.

I used:
`$ gsettings set com.github.geigi.cozy last-launched-version '1.2.1'`

Now it works fine.

I've seen in this repo that is has already been fixed, is there anyway to get the true latest version ? I feel like i'm using an old one.

**Comment by rdbende** [comment]
To get the latest version of Cozy, we recommend using the [Flatpak package from Flathub](https://flathub.org/apps/com.github.geigi.cozy)

Even though the PPA says "cozy-team" it is not an official distribution from us, and looks like it wasn't updated in a while.
