### ISSUE TITLE
packaging.version.InvalidVersion: Invalid version: 'None'

### ISSUE THREAD

**Issue by bbhtt** [geigi/cozy#788]
### Bug/Feature description

With packaging-23.0 the program crashes instantly:

```
$ flatpak run com.github.geigi.cozy 
                                                             
['/app/bin/com.github.geigi.cozy']
09:38:20 [MainThread  ] [applicatio] [INFO ]  ('org.gnome.platform', '45', 'Flatpak runtime')
09:38:20 [MainThread  ] [applicatio] [INFO ]  Starting up cozy 1.2.1
09:38:20 [MainThread  ] [db        ] [INFO ]  SQLite version: 3.42.0
09:38:20 [Thread-1 (ru] [peewee.sql] [INFO ]  writer received shutdown request, exiting.
09:38:20 [MainThread  ] [applicatio] [INFO ]  libhandy version: 1
handle exception
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/cozy/application.py", line 99, in do_activate
    self.app_controller = AppController(self, main_window_builder, self.ui)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/cozy/architecture/singleton.py", line 5, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/cozy/app_controller.py", line 52, in __init__
    self.whats_new_window: WhatsNewWindow = WhatsNewWindow()
                                            ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/cozy/ui/widgets/whats_new_window.py", line 36, in __init__
    self._fill_window()
  File "/app/lib/python3.11/site-packages/cozy/ui/widgets/whats_new_window.py", line 54, in _fill_window
    last_launched_version = version.parse(self.app_settings.last_launched_version)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/packaging/version.py", line 197, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'None
```

Seems there should be a version constraint here https://github.com/geigi/cozy/blob/1b640d1f61aa8a610a91427567c0d7f2df4e86bd/requirements.txt#L3

### System Information
- Operating System: Fedora 39
- Installation source: flatpak
- Version of cozy: 1.2.1

**Comment by bbhtt** [comment]
Erm, just found this is a dupe of https://github.com/geigi/cozy/issues/756 sorry.
