### ISSUE TITLE
Flatpak installation does not execute on Fedora 39

### ISSUE THREAD

**Issue by lamyergeier** [geigi/cozy#793]
### Bug/Feature description

- Flatpak installation:

```
Looking for matches…

com.github.geigi.cozy permissions:
    ipc                    network                  fallback-x11        pulseaudio
    wayland                x11                      dri                 file access [1]
    dbus access [2]        bus ownership [3]

    [1] host, xdg-run/gvfs, xdg-run/gvfsd
    [2] org.freedesktop.Notifications, org.gtk.vfs.*
    [3] org.mpris.MediaPlayer2.Cozy


        ID                                   Branch      Op Remote  Download
 1. [✓] com.github.geigi.cozy.Locale         stable      i  flathub  3.4 kB / 170.6 kB
 2. [✓] org.freedesktop.Platform.GL.default  23.08       u  flathub 43.9 MB / 163.6 MB
 3. [✓] org.freedesktop.Platform.GL.default  23.08-extra u  flathub 31.9 MB / 163.6 MB
 4. [✓] org.freedesktop.Platform.VAAPI.Intel 23.08       u  flathub  2.9 kB / 13.4 MB
 5. [✓] org.gnome.Platform.Locale            45          u  flathub 18.1 kB / 365.1 MB
 6. [✓] org.gnome.Platform                   45          u  flathub 23.2 MB / 370.5 MB
 7. [✓] com.github.geigi.cozy                stable      i  flathub  4.2 MB / 3.9 MB

Changes complete.
```

- Error when executing

```
$ cozy
/app/lib/python3.11/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.11) or chardet (None)/charset_normalizer (3.2.0) doesn't match a supported version!
  warnings.warn(
['/app/bin/com.github.geigi.cozy']

(com.github.geigi.cozy:2): Gtk-WARNING **: 21:56:05.626: Theme parsing error: gtk.css:10419:21: Not using units is deprecated. Assuming 'px'.
21:56:05 [MainThread  ] [applicatio] [INFO ]  ('org.gnome.platform', '45', 'Flatpak runtime')
21:56:05 [MainThread  ] [applicatio] [INFO ]  Starting up cozy 1.2.1
21:56:05 [MainThread  ] [db        ] [INFO ]  SQLite version: 3.42.0
21:56:05 [Thread-1 (ru] [peewee.sql] [INFO ]  writer received shutdown request, exiting.

(com.github.geigi.cozy:2): Gtk-WARNING **: 21:56:05.824: Theme parsing error: gtk.css:10419:21: Not using units is deprecated. Assuming 'px'.

(com.github.geigi.cozy:2): Gtk-WARNING **: 21:56:05.965: Theme parsing error: gtk.css:10419:21: Not using units is deprecated. Assuming 'px'.

(com.github.geigi.cozy:2): Gtk-WARNING **: 21:56:06.108: Theme parsing error: gtk-dark.css:10402:21: Not using units is deprecated. Assuming 'px'.

(com.github.geigi.cozy:2): Gtk-WARNING **: 21:56:06.242: Theme parsing error: gtk-dark.css:10402:21: Not using units is deprecated. Assuming 'px'.
21:56:06 [MainThread  ] [applicatio] [INFO ]  libhandy version: 1
handle exception
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/cozy/application.py", line 99, in do_activate
    self.app_controller = AppController(self, main_window_builder, self.ui)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/cozy/architecture/singleton.py", line 5, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/cozy/app_controller.py", line 52, in __init__
    self.whats_new_window: WhatsNewWindow = WhatsNewWindow()
                                            ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/cozy/ui/widgets/whats_new_window.py", line 36, in __init__
    self._fill_window()
  File "/app/lib/python3.11/site-packages/cozy/ui/widgets/whats_new_window.py", line 54, in _fill_window
    last_launched_version = version.parse(self.app_settings.last_launched_version)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamy/.local/lib/python3.11/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/home/lamy/.local/lib/python3.11/site-packages/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'None'
```

### System Information
- Operating System:  Fedora 38
- Installation source:  Flatpak
- Version of cozy: 23.08

**Comment by mojolo** [comment]
Same error here with Cozy 1.2.1 installed via Ubuntu PPA.

Kubuntu 23.04

**Comment by rdbende** [comment]
Was fixed in #762

**Comment by lamyergeier** [comment]
@rdbende  I tried again today in Fedora 39

```
Looking for matches…

com.github.geigi.cozy permissions:
    ipc                    network                  fallback-x11       pulseaudio
    wayland                x11                      dri                file access [1]
    dbus access [2]        bus ownership [3]

    [1] host, xdg-run/gvfs, xdg-run/gvfsd
    [2] org.freedesktop.Notifications, org.gtk.vfs.*
    [3] org.mpris.MediaPlayer2.Cozy


        ID                               Branch     Op     Remote     Download
 1. [✓] com.github.geigi.cozy.Locale     stable     i      flathub    3.4 kB / 170.6 kB
 2. [✓] com.github.geigi.cozy            stable     i      flathub    2.6 MB / 3.9 MB

Installation complete.
```

```
$ cozy
/app/lib/python3.11/site-packages/requests/__init__.py:109: RequestsDependencyWarning: urllib3 (2.1.0) or chardet (None)/charset_normalizer (3.3.2) doesn't match a supported version!
  warnings.warn(
['/app/bin/com.github.geigi.cozy']

(com.github.geigi.cozy:2): Gtk-WARNING **: 13:58:26.467: Theme parsing error: gtk.css:10419:21: Not using units is deprecated. Assuming 'px'.
13:58:26 [MainThread  ] [applicatio] [INFO ]  ('org.gnome.platform', '45', 'Flatpak runtime')
13:58:26 [MainThread  ] [applicatio] [INFO ]  Starting up cozy 1.2.1
13:58:26 [MainThread  ] [db        ] [INFO ]  SQLite version: 3.42.0
13:58:26 [Thread-1 (ru] [peewee.sql] [INFO ]  writer received shutdown request, exiting.

(com.github.geigi.cozy:2): Gtk-WARNING **: 13:58:26.665: Theme parsing error: gtk.css:10419:21: Not using units is deprecated. Assuming 'px'.

(com.github.geigi.cozy:2): Gtk-WARNING **: 13:58:26.844: Theme parsing error: gtk.css:10419:21: Not using units is deprecated. Assuming 'px'.

(com.github.geigi.cozy:2): Gtk-WARNING **: 13:58:26.989: Theme parsing error: gtk-dark.css:10402:21: Not using units is deprecated. Assuming 'px'.

(com.github.geigi.cozy:2): Gtk-WARNING **: 13:58:27.142: Theme parsing error: gtk-dark.css:10402:21: Not using units is deprecated. Assuming 'px'.
13:58:27 [MainThread  ] [applicatio] [INFO ]  libhandy version: 1
handle exception
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/cozy/application.py", line 99, in do_activate
    self.app_controller = AppController(self, main_window_builder, self.ui)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/cozy/architecture/singleton.py", line 5, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/cozy/app_controller.py", line 52, in __init__
    self.whats_new_window: WhatsNewWindow = WhatsNewWindow()
                                            ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/cozy/ui/widgets/whats_new_window.py", line 36, in __init__
    self._fill_window()
  File "/app/lib/python3.11/site-packages/cozy/ui/widgets/whats_new_window.py", line 54, in _fill_window
    last_launched_version = version.parse(self.app_settings.last_launched_version)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lamy/.local/lib/python3.11/site-packages/packaging/version.py", line 54, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/home/lamy/.local/lib/python3.11/site-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'None'
```

**Comment by rdbende** [comment]
It was fixed in the current development branch. It's not yet on Flathub.

**Comment by rdbende** [comment]
There will be soon. Until then, you can try the beta version:

```
flatpak --user remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak --user install flathub-beta com.github.geigi.cozy
```
